### ISSUE TITLE
Crash while login with Twitter

### ISSUE THREAD

**Issue by swapnalishinde** [oneall/ios-sdk#4]
Hi,
I am trying to integrate this in my iOS application with Advanced plan.
But the problem I am facing is that It gives me crash while launching the Twitter login page saying "Performing reverse auth for account --"

The crash report says-
 +[NSString ab_GUID]: unrecognized selector sent to class 0x1ada5dae8

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSString ab_GUID]: unrecognized selector sent to class 0x1ada5dae8'

Can you please help me sort this out?

Thanks in advance!

**Comment by swapnalishinde** [comment]
Hey guys, Issue is resolved.
It was due to the following reason-
Your 3rd party framework is probable using a category on a existing (apple) class. But to load/find the category you need to add the -ObjC flag in the build settings under Other Linker Flags
Ref link- 
https://stackoverflow.com/questions/10442653/unrecognized-selector-calling-category-method-in-static-ios-library

**Comment by SchlesserClaude** [comment]
Great! Thank you for the solution! I have added it to the readme:
https://github.com/oneall/ios-sdk/blob/master/README.md#build-settings
