### ISSUE TITLE
Not able to launch facebook login

### ISSUE THREAD

**Issue by swapnalishinde** [oneall/ios-sdk#6]
Hello Team,

I am facing this issue-
![simulator screen shot 22-aug-2017 10 55 30 pm](https://user-images.githubusercontent.com/5267845/29578523-2973ac36-878d-11e7-8560-7b65a6274803.png)

**Comment by SchlesserClaude** [comment]
Hello,

you can enable one-time-tokens in the API settings of your site in your OneAll account.
Enabling it will make the error disappear.

Regards,

**Comment by swapnalishinde** [comment]
Thanks!
It worked like a charm :)
